language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
matrix:
  include:
    - jdk:
        - openjdk11
      env: jdk.release=11
    - jdk:
        - openjdk14
      env: jdk.release=14
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    - jdk:
        - openjdk15
        env: jdk.release=15
        before_install:
          - rm "${JAVA_HOME}/lib/security/cacerts"
          - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
install: true
branches:
  only:
    - master
script:
  - mvn clean install -Djdk.release=${release}